#!/usr/bin/env bash
# Configures a new Ubuntu machine to meet the task requirements

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Add custom header to nginx configuration
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        add_header X-Served-By $hostname;
        try_files $uri $uri/ =404;
    }
}' > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
