#!/usr/bin/env bash
# Configures Nginx to return "Hello Holberton" on port 80 and then stops the service
apt-get update
apt-get install -y nginx
echo "Hello Holberton" > /var/www/html/index.nginx-debian.html
service nginx start
service nginx stop
